## Required Parameters:
# input_dir || remote_input_dir
# output_dir
# gffquant_db

## Optional Parameters
# ignore_dirs
# bam_input_pattern
# gq_min_seqlen
# gq_min_identity
# large_reference
# gq_unmarked_orphans
# gq_mode
# gq_ambig_mode
# gq_db_coordinates
# gq_db_separator
# gq_output
# gq_dbformat
# collate_gene_counts
# do_name_sort
# gq_collate_columns

############ i/o parameters ###################################################
###############################################################################

## Either input_dir or remote_input_dir are required. They are mutually exclusive!
input_dir: "<YOUR_DATA>" # string, use if the input metagenomes are local. Will only create symlinks to the original data

# remote_input_dir: # use if the input is remote somewhere. 
## This will copy the files if they are compressed fastqs with fq.gz, fastq.gz, fastq.bz2, or fq.bz2 suffix, are named according to  the _R1/_R2 naming convention and have only 1 (single-end) or 2 (paired-end) files per sample. In all other cases, files will be renamed, compressed, concatenated etc. on demand, such that for each sample there will be at most 1 file for single-end libraries, 2 files for paired-end libraries, or 3 files for preprocessed paired-end libraries.

# ignore_dirs: "testing_data" # comma separated list of directories of the input which get ignored, optional

# bam_input_pattern: "**.bam"	# string, set in /nevermore/workflows/input.nf #optional

## store output as bam files or as fastq files?
# do_bam2fq_conversion: false # boolean, optional

## Where are the final results published?
output_dir: "nevermore_output" # string, required

###################### gffquant ########################
## path to functional annotation reference DB
gffquant_db: "/scratch/schudoma/databases/gmgc/GMGC10.human-gut.95nr.0.5pv.20230422.2101.sqlite3" # on EMBL cluster
# gffquant_db: "/exports/archive/lucid-grpzeller-primary/SHARED/DATA/gene_catalogues/GMGC_reduced_0_5_prevalence/GMGC_emapper_annotations/GMGC10.human-gut.95nr.0.5pv.20230422.2101.sqlite3" # on LUMC shark cluster

# gq_strand_specific # boolean, optional, default empty, whether to set the --strand_specific flag
gq_min_seqlen: 45 # integer, optional, default not set
gq_min_identity: 0.97 # integer, optional, default not set

## is this a large reference? e.g. GMGC global -> will cause aligner to write sam instead of bam
# large_reference # optional will only have an effect if bam_input_pattern not set

# gq_restrict_metrics # optional, default not set
gq_unmarked_orphans: true # boolean, optional, default empty, whether to set the --unmarked_orphans flag

# if dealing with cazymes set it to "domain" - see current issue
gq_mode: "genes" # conditionally required, if set to "domain" it adds the following flags: " --db_separator , --db_coordinates hmmer"
gq_ambig_mode: "1overN" # conditionally required
# gq_db_coordinates  # conditionally required
# gq_db_separator  # conditionally required
# gq_output # conditionally required

do_name_sort: true # boolean, optional
## gffquant requires the input-alignments to be name-sorted, if the bams are not name-sorted, this causes 'samtools collate' to be ran, which sorts the input by name (quicker than samtools sort -n)

# no_collate: false # optional, default is false, do not collate files
# collate_gene_counts: true #  optional, default is true, removes files ending with “gene_counts.txt.gz” from feature counts if the collate_gene_counts parameter is false
# gq_collate_columns # optional, default is "uniq_scaled,combined_scaled" set in /nevermore/workflows/gffquant.nf